#Sky Force - Player Save Data
<<<<<<< HEAD
#Wed Aug 19 00:47:06 GMT+07:00 2026
equipped_skin=green
high_score=905
total_gold=1003849
=======
#Tue Aug 18 23:36:11 GMT+07:00 2026
equipped_skin=green
high_score=905
total_gold=1003627
>>>>>>> 18f6adfada2ef43d4f1b6c32d5061fc00e383ce4
unlocked_skins=orange,red,green,blue
