#Sky Force - Player Save Data
#Wed Aug 19 01:44:03 GMT+07:00 2026
equipped_skin=green
high_score=5
high_score1=5
high_score2=0
high_score3=0
high_score4=0
total_gold=1003744
unlocked_skins=orange,red,green,blue
