#Sky Force - Player Save Data
#Thu Aug 20 12:33:35 GMT+07:00 2026
equipped_skin=blue
high_score=595
high_score1=615
high_score2=635
high_score3=895
high_score4=595
total_gold=5034
unlocked_skins=blue
